dist: trusty
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - jruby-1.7.26
  - jruby-9.2.4.0
env:
  global:
    - JRUBY_OPTS="--debug"
after_success:
  - bundle exec codeclimate-test-reporter
