dist: trusty
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - jruby-1.7.26
  - jruby-9.1.14.0
env:
  global:
    - JRUBY_OPTS="--debug"
after_success:
  - bundle exec codeclimate-test-reporter
