---
os: linux
dist: xenial

language: ruby
cache: bundler
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - jruby-9.2.13.0
env:
  global:
    - JRUBY_OPTS="--debug"
after_success:
  - bundle exec codeclimate-test-reporter
