language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - jruby-1.7.20
  - jruby-9.1.7.0
env:
  global:
    - JRUBY_OPTS="--debug"
after_success:
  - bundle exec codeclimate-test-reporter
